# Generated by Django 5.2.6 on 2025-10-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorias", "0002_alter_category_options_alter_category_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("cost", models.IntegerField()),
                ("image", models.ImageField(upload_to="imgs/products/")),
                ("stock", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("date_register", models.DateField(auto_now_add=True)),
                ("date_update", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categorias.category",
                    ),
                ),
            ],
        ),
    ]
