# Generated by Django 5.2.6 on 2025-10-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(max_length=30)),
                ("description", models.CharField(max_length=20)),
            ],
        ),
    ]
