# Generated by Django 5.2.6 on 2025-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoría", "verbose_name_plural": "Categorías"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
